baseURL = "https://www.glads.fr"
title = "GLADS | Architecture · Développement · Sécurité · Informatique"
defaultContentLanguage = "fr"

enableRobotsTXT = true
enableGitInfo = true
disableKinds = ["taxonomy", "term", "section"]

[frontmatter]
  lastmod = [":git", "lastmod", ":fileModTime"]

[languages]
  [languages.fr]
    languageCode = "fr-FR"
    contentDir = "content/fr"
    languageName = "Français"
    weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true
